// Generated by CoffeeScript 1.9.0
(function(doc) {
  if (doc.collection === "user" || doc.collection === "question") {
    emit(doc._id, null);
  }
  if (doc.isApplicationDoc === true) {
    return emit(doc._id, null);
  }
});

//# sourceMappingURL=map.js.map
