// Generated by CoffeeScript 1.9.0
var ReportView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

ReportView = (function(_super) {
  __extends(ReportView, _super);

  function ReportView() {
    this.spreadsheet = __bind(this.spreadsheet, this);
    this.render = __bind(this.render, this);
    this.update = __bind(this.update, this);
    return ReportView.__super__.constructor.apply(this, arguments);
  }

  ReportView.prototype.el = '#content';

  ReportView.prototype.events = {
    "change #reportOptions": "update",
    "change #summaryField": "summarize",
    "change #aggregateBy": "update",
    "click #toggleDisaggregation": "toggleDisaggregation"
  };

  ReportView.prototype.update = function() {
    var reportOptions, url;
    reportOptions = {
      startDate: $('#start').val(),
      endDate: $('#end').val(),
      reportType: $('#report-type :selected').text(),
      question: $('#selected-question :selected').text(),
      aggregateBy: $("#aggregateBy :selected").text()
    };
    _.each(this.locationTypes, function(location) {
      return reportOptions[location] = $("#" + location + " :selected").text();
    });
    url = "reports/" + _.map(reportOptions, function(value, key) {
      return key + "/" + (escape(value));
    }).join("/");
    return Coconut.router.navigate(url, true);
  };

  ReportView.prototype.render = function(options) {
    this.reportType = options.reportType || "results";
    this.startDate = options.startDate || moment(new Date).subtract('days', 14).format("YYYY-MM-DD");
    this.endDate = options.endDate || moment(new Date).format("YYYY-MM-DD");
    this.question = unescape(options.question);
    this.aggregateBy = options.aggregateBy || "District";
    this.$el.html("<style> table.results th.header, table.results td{ font-size:150%; } </style> <table id='reportOptions'></table> <div id='report'></div>");
    return Coconut.questions.fetch({
      success: (function(_this) {
        return function() {
          $("#reportOptions").append(_this.formFilterTemplate({
            id: "question",
            label: "Question",
            form: "<select id='selected-question'> " + (Coconut.questions.map(function(question) {
              return "<option " + (question.label() === _this.question ? "selected='true'" : "") + ">" + (question.label()) + "</option>";
            }).join("")) + " </select>"
          }));
          $("#reportOptions").append(_this.formFilterTemplate({
            id: "start",
            label: "Start Date",
            form: "<input id='start' type='date' value='" + _this.startDate + "'/>"
          }));
          $("#reportOptions").append(_this.formFilterTemplate({
            id: "end",
            label: "End Date",
            form: "<input id='end' type='date' value='" + _this.endDate + "'/>"
          }));
          $("#reportOptions").append(_this.formFilterTemplate({
            id: "report-type",
            label: "Report Type",
            form: "<select id='report-type'> " + (_.map(["results", "spreadsheet", "pivotTable", "summarytables"], function(type) {
              return "<option " + (type === _this.reportType ? "selected='true'" : void 0) + ">" + type + "</option>";
            }).join("")) + " </select>"
          }));
          _this[_this.reportType]();
          $('div[data-role=fieldcontain]').fieldcontain();
          $('select').selectmenu();
          return $('input[type=date]').datebox({
            mode: "calbox"
          });
        };
      })(this)
    });
  };

  ReportView.prototype.hierarchyOptions = function(locationType, location) {
    if (locationType === "region") {
      return _.keys(WardHierarchy.hierarchy);
    }
    return _.chain(WardHierarchy.hierarchy).map(function(value, key) {
      if (locationType === "district" && location === key) {
        return _.keys(value);
      }
      return _.map(value, function(value, key) {
        if (locationType === "constituan" && location === key) {
          return _.keys(value);
        }
        return _.map(value, function(value, key) {
          if (locationType === "shehia" && location === key) {
            return value;
          }
        });
      });
    }).flatten().compact().value();
  };

  ReportView.prototype.mostSpecificLocationSelected = function() {
    var mostSpecificLocationType, mostSpecificLocationValue;
    mostSpecificLocationType = "region";
    mostSpecificLocationValue = "ALL";
    _.each(this.locationTypes, function(locationType) {
      if (this[locationType] !== "ALL") {
        mostSpecificLocationType = locationType;
        return mostSpecificLocationValue = this[locationType];
      }
    });
    return {
      type: mostSpecificLocationType,
      name: mostSpecificLocationValue
    };
  };

  ReportView.prototype.formFilterTemplate = function(options) {
    return "<tr> <td> <label style='display:inline' for='" + options.id + "'>" + options.label + "</label> </td> <td style='width:150%'> " + options.form + " </select> </td> </tr>";
  };

  ReportView.prototype.viewQuery = function(options) {
    var results;
    results = new ResultCollection();
    return results.fetch({
      question: $('#selected-question').val(),
      isComplete: true,
      include_docs: true,
      success: function() {
        results.fields = {};
        results.each(function(result) {
          return _.each(_.keys(result.attributes), function(key) {
            if (!_.contains(["_id", "_rev", "question"], key)) {
              return results.fields[key] = true;
            }
          });
        });
        results.fields = _.keys(results.fields);
        return options.success(results);
      }
    });
  };

  ReportView.prototype.spreadsheet = function() {
    var endkey;
    $("#report").html("<table id='reportTable'> <thead> <tr/> </thead> <tbody> </tbody> </table>");
    if (this.endDate) {
      endkey = moment(this.endDate).endOf("day").format("YYYY-MM-DD HH:mm:ss");
    }
    return $.couch.db(Coconut.config.database_name()).view((Coconut.config.design_doc_name()) + "/results", {
      startkey: [this.question, this.startDate || null],
      endkey: [this.question, endkey || {}],
      include_docs: true,
      error: (function(_this) {
        return function(error) {
          return console.log(JSON.stringify(error));
        };
      })(this),
      success: (function(_this) {
        return function(results) {
          var fields;
          results = results.rows;
          fields = {};
          _(results).each(function(result) {
            return _(_(result.doc).keys()).each(function(key) {
              return fields[key] = true;
            });
          });
          fields = _(fields).keys();
          $("#reportTable thead tr").html(_(fields).map(function(field) {
            return "<th>" + field + "</th>";
          }).join(""));
          $("#reportTable tbody").html(_(results).map(function(result) {
            return "<tr> " + (_(fields).map(function(field) {
              return "<td>" + (result.doc[field] || "-") + "</td>";
            }).join("")) + " </tr>";
          }).join(""));
          $("#report").css("overflow", "scroll");
          return $("#reportTable").dataTable({
            aaSorting: [[0, "desc"]],
            iDisplayLength: 25,
            dom: 'T<"clear">lfrtip',
            tableTools: {
              sSwfPath: "js-libraries/copy_csv_xls_pdf.swf"
            }
          });
        };
      })(this)
    });
  };

  ReportView.prototype.pivotTable = function() {
    var endkey;
    if (this.endDate) {
      endkey = moment(this.endDate).endOf("day").format("YYYY-MM-DD HH:mm:ss");
    }
    return $.couch.db(Coconut.config.database_name()).view((Coconut.config.design_doc_name()) + "/results", {
      startkey: [this.question, this.startDate || null],
      endkey: [this.question, endkey || {}],
      include_docs: true,
      error: (function(_this) {
        return function(error) {
          return console.log(JSON.stringify(error));
        };
      })(this),
      success: (function(_this) {
        return function(results) {
          return console.log(_(results.rows).pluck("doc", $("#report").pivotUI(_(results.rows).pluck("doc"), {
            renderers: $.extend($.pivotUtilities.renderers, $.pivotUtilities.gchart_renderers, $.pivotUtilities.d3_renderers)
          })));
        };
      })(this)
    });
  };

  ReportView.prototype.results = function() {
    var endkey;
    if (this.endDate) {
      endkey = moment(this.endDate).endOf("day").format("YYYY-MM-DD HH:mm:ss");
    }
    return $.couch.db(Coconut.config.database_name()).view((Coconut.config.design_doc_name()) + "/results", {
      startkey: [this.question, this.startDate || null],
      endkey: [this.question, endkey || {}],
      include_docs: true,
      error: (function(_this) {
        return function(error) {
          return console.log(JSON.stringify(error));
        };
      })(this),
      success: (function(_this) {
        return function(results) {
          return _this.$el.append("<h2>" + _this.question + ": " + results.rows.length + " results for " + _this.startDate + " - " + _this.endDate + "</h2> Select another report type above for further analysis");
        };
      })(this)
    });
  };

  ReportView.prototype.summarytables = function() {
    return Coconut.resultCollection.fetch({
      includeData: true,
      success: (function(_this) {
        return function() {
          var fields;
          fields = _.chain(Coconut.resultCollection.toJSON()).map(function(result) {
            return _.keys(result);
          }).flatten().uniq().sort().value();
          fields = _.without(fields, "_id", "_rev");
          _this.$el.append("<br/> Choose a field to summarize:<br/> <select id='summaryField'> " + (_.map(fields, function(field) {
            return "<option id='" + field + "'>" + field + "</option>";
          }).join("")) + " </select>");
          return $('select').selectmenu();
        };
      })(this)
    });
  };

  ReportView.prototype.summarize = function() {
    var field;
    field = $('#summaryField option:selected').text();
    return this.viewQuery({
      success: (function(_this) {
        return function(resultCollection) {
          var results;
          results = {};
          resultCollection.each(function(result) {
            return _.each(result.toJSON(), function(value, key) {
              if (key === field) {
                if (results[value] != null) {
                  results[value]["sums"] += 1;
                  return results[value]["resultIDs"].push(result.get("_id"));
                } else {
                  results[value] = {};
                  results[value]["sums"] = 1;
                  results[value]["resultIDs"] = [];
                  return results[value]["resultIDs"].push(result.get("_id"));
                }
              }
            });
          });
          _this.$el.append("<h2>" + field + "</h2> <table id='summaryTable' class='tablesorter'> <thead> <tr> <th>Value</th> <th>Total</th> </tr> </thead> <tbody> " + (_.map(results, function(aggregates, value) {
            return "<tr> <td>" + value + "</td> <td> <button id='toggleDisaggregation'>" + aggregates["sums"] + "</button> </td> <td class='dissaggregatedResults'> " + (_.map(aggregates["resultIDs"], function(resultID) {
              return resultID;
            }).join(", ")) + " </td> </tr>";
          }).join("")) + " </tbody> </table>");
          $("button").button();
          $("a").button();
          return _.each($('table tr'), function(row, index) {
            if (index % 2 === 1) {
              return $(row).addClass("odd");
            }
          });
        };
      })(this)
    });
  };

  ReportView.prototype.toggleDisaggregation = function() {
    return $(".dissaggregatedResults").toggle();
  };

  return ReportView;

})(Backbone.View);

//# sourceMappingURL=ReportView.js.map
